=== TP-XML-LUMINY/Projet/src/dtd/master.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY menu SYSTEM "../xml/menu.xml">
<!ENTITY  programme SYSTEM "../xml/Unites.xml">

<!ELEMENT master (menu?,(parcours)+)>
<!ELEMENT parcours (intervenants?,presentation,competences?,connaissances?,programme*,politique_des_stages?,aspects_formation?,modalites_pedagogiques?,enseignements_delocalises?,conditions_admission?,debouches?,poursuites?)>

<!ELEMENT menu (lien)+>
<!ELEMENT intervenants (enseignant)*>
<!ELEMENT presentation ((enseignant|refprof)*,lieu?,description?)>
<!ELEMENT competences (paragraphe|liste)+>
<!ELEMENT connaissances (paragraphe|liste)+>
<!ELEMENT programme (paquet_unites)*>
<!ELEMENT politique_des_stages (paragraphe|liste)+>
<!ELEMENT aspects_formation (paragraphe|liste)+>
<!ELEMENT modalites_pedagogiques (paragraphe|liste)+>
<!ELEMENT enseignements_delocalises (paragraphe|liste)+>
<!ELEMENT conditions_admission (pre_requis*,paragraphe*,lien)>
<!ELEMENT debouches (paragraphe|liste)+>
<!ELEMENT poursuites (paragraphe|liste)+>

<!ELEMENT enseignant (nom,prenom?,mail+,site_web*)>
<!ELEMENT lieu (campus)+>
<!ELEMENT description (paragraphe|liste)+>
<!ELEMENT paquet_unites (nom?,(unite|refunite)+)>
<!ELEMENT unite (nom,credit,(refprof|resumes|plan|lieu)*)>
<!ELEMENT refunite EMPTY>
<!ELEMENT plan (nom,nb_h)>
<!ELEMENT resumes (((paragraphe|chapitre|liste)+,pre_requis?)|(absent))>
<!ELEMENT absent EMPTY>
<!ELEMENT chapitre (titre,(paragraphe|liste)*)>
<!ELEMENT pre_requis (paragraphe|liste)+>

<!ELEMENT nb_h (#PCDATA)>
<!ELEMENT titre (#PCDATA|b|i|tt|u)*>
<!ELEMENT nom (#PCDATA|b|i|tt|u)*>
<!ELEMENT prenom (#PCDATA|b|i|tt|u)*>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT campus (#PCDATA|b|i|tt|u)*>
<!ELEMENT paragraphe (#PCDATA|b|i|tt|u|liste)*>
<!ELEMENT site_web (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT refprof EMPTY>
<!ELEMENT resume (#PCDATA|b|i|tt|u)*>
<!ELEMENT lien (#PCDATA|b|i|tt|u)*>
<!ELEMENT liste (paragraphe?,(el)+)>

<!ELEMENT el (#PCDATA|b|i|tt|u)*>
<!ELEMENT b	(#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT tt (#PCDATA)>
<!ELEMENT u (#PCDATA)>

<!ATTLIST pre_requis
	type CDATA #IMPLIED
	>
<!ATTLIST liste
	type CDATA "ul"
	>
<!ATTLIST parcours
	annee CDATA #REQUIRED
	>
<!ATTLIST programme
	semestre CDATA #REQUIRED
	>
<!ATTLIST enseignant
	id ID #IMPLIED
	>
<!ATTLIST unite
	id ID #REQUIRED
	>
<!ATTLIST refunite
	id CDATA #REQUIRED
	>
<!ATTLIST ref
	idref IDREF #REQUIRED
	>
<!ATTLIST refprof
	id CDATA #REQUIRED
	>
<!ATTLIST lien
	link CDATA #REQUIRED
	class CDATA #IMPLIED
	>

=== TP-XML-LUMINY/Projet/src/xml/FED.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="FED">
		<presentation>
			<refprof id="noel.novelli"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>Ce parcours permet aux étudiants d’approfondir les connaissances qu'ils doivent maîtriser pour appréhender le cycle de vie complet des bases et entrepôts de données : de leur conception à leur administration, en passant par les architectures logicielles des systèmes de bases de données, et les divers formats d'échanges à travers le web. Une attention particulière est portée à l'étude des techniques de fouille et d'extraction de connaissances à partir de données. La Fouille de Données ou l'Extraction de Connaissances à partir de Bases de données désigne un domaine de compétences dont l'objectif est de rechercher et découvrir des informations, nouvelles et utiles, dans des données le plus souvent volumineuses et hétérogènes. La fouille de données rassemble des professionnels de plusieurs disciplines : des spécialistes en bases et entrepôts de données, en analyse des données, ayant aussi des connaissances de bases en recherche opérationnelle.</paragraphe>
			</description>
		</presentation>
		<competences>
			<liste>
				<el>Anglais, Communication et JEE.</el>
				<el>Créer, maintenir et optimiser des bases de données et/ou des entrepôts de données.</el>
				<el>Mettre en place des solutions de fouilles de données pour diverses domaines comme le marketing, les études de produits et de clientèle, l’aide à la décision, la veille technologique...</el>
				<el>Optimisation combinatoire, programmation mathématique, langages de modélisation, algorithmique des graphes et réseaux.</el>
			</liste>
		</competences>
		<connaissances>
			<paragraphe>Outre les connaissances généralistes comme l’anglais, la communication et JEE (Java Enterprise Edition), les étudiants acquerront les notions fondamentales de l’Informatique Décisionnelle qui regroupe l’administration de bases de données et la modélisation des problèmes (concevoir et constituer un réservoir exploitable de données et définir la stratégie d’exploitation en vue d’une analyse de données), l’optimisation linéaire (modéliser et résoudre un problème d’optimisation), la fouille de bases de données (extraire des informations intéressantes non préalablement connues).</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Tronc-commun des parcours FED et RO </nom>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
				<refunite id="ENSINCU30"/>
				<refunite id="ENSINCU40"/>
				<refunite id="ENSINCU48"/>
				<refunite id="ENSINCU49"/>
				<refunite id="ENSINCU50"/>
				<refunite id="ENSINCU70"/>
				<refunite id="ENSINCU53"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unité d'enseignement à bonus</nom>
				<refunite id="ENSINCU67"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINCU52"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les stages sont optionnels en première année (2 mois), obligatoires en deuxième année (4 à 6 mois). La recherche de stage est assurée par l'étudiant avec l'aide de l'équipe pédagogique (liste d'entreprises, diffusion des offres reçues, etc.). Le sujet de stage est validé par un enseignant responsable avant la signature de la convention. Les sujets doivent vérifier un cahier des charges qui est donné aux étudiants en début d'année. Le stage peut alors débuter. Durant la période de stage, un rapport d'avancement est demandé régulièrement au stagiaire (tous les mois). Les éventuels problèmes sont ainsi décelés au plus tôt. A l'issue du stage, le stagiaire doit fournir un rapport de stage et faire une soutenance orale. Il est noté sur la base de son rapport, de sa présentation et de l'évaluation du stage faite par son tuteur en entreprise.</paragraphe>
		</politique_des_stages>
		<enseignements_delocalises>
			<paragraphe>Ce master bénéficie de plusieurs contrats Erasmus. Trois contrats de longue date avec les universités de Tübingen et Hannovre (Allemagne) et avec l'université anglophone d'Uppsala (Suède) ont déjà permis des échanges d'étudiants en M1 et M2. Un contrat plus récent avec les université techniques de Munich (Allemagne) et Vienne (Autriche) sont actifs et permettent également des échanges au niveau Master 1 et 2 (le plus souvent sur un semestre), puis au niveau doctoral.</paragraphe>
			<liste>
				<paragraphe>Établissements avec lesquels nous avons un accord Erasmus :</paragraphe>
				<el>Allemagne, Hannovre, Gottfried Wilhelm Leibniz Universität</el>
				<el>Allemagne, Munich, Technische Universität München</el>
				<el>Allemagne, Tübingen, Eberhard Karls Universität</el>
				<el>Vienne, Autriche, Technische Universität Wien</el>
				<el>Suède, Uppsala, Uppsala Universitet</el>
			</liste>
			<liste>
				<paragraphe>Autres établissements avec lesquels nous avons un accord :</paragraphe>
				<el>Belgique, Namur, Facultés Universitaires Notre Dame de la Paix</el>
				<el>Bulgarie, Sofia, Tehnicheski Universitet</el>
				<el>Espagne, Séville, Universidad de Sevilla</el>
				<el>Italie, Sienne, Univ. di Siena</el>
				<el>Roumanie, Brasov, Universitatea Transilvania din Brasov</el>
			</liste>
			<liste>
				<paragraphe>Établissements canadiens avec lesquels nous avons un accord :</paragraphe>
				<el>Université de Montréal</el>
				<el>Université d'Ottawa</el>
				<el>Université de Victoria</el>
				<el>Université Western Ontario</el>
			</liste>
		</enseignements_delocalises>
		<conditions_admission>
			<paragraphe>Après l'étude des dossiers des candidats, le jury d'admission constitué à partir des membres de l'équipe pédagogique statue sur l'admission de chacun d'eux.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<liste>
				<el>Administrateur de bases de données ou d’entrepôts de données.</el>
				<el>Extraction, transformation et chargement des données.</el>
				<el>Gestion, exploitation et optimisation de bases et entrepôts de données.</el>
				<el>Mettre en place et exploiter toutes les phases du processus de l’informatique décisionnelle (compréhension et modélisation du problème, conception du système d’information nécessaire, indicateur de mesure pour réaliser les analyses pour la prise de décisions, les processus de fouille et d’optimisation, la restitution de l’analyse).</el>
				<el>Études et développement informatique.</el>
				<el>Conseil et maîtrise d’ouvrage en système d’information</el>
				<el>Expertise et support technique en système d’information</el>
				<el>Administration de systèmes d'information</el>
			</liste>
		</debouches>
		<poursuites>
			<paragraphe>Il est possible de poursuivre en thèse de doctorat notamment grâce à des bourses CIFRE en partenariat avec des entreprises.</paragraphe>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/xml/SIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="SIS">
		<presentation>
			<refprof id="isabel.demongodin"/>
			<description>
				<paragraphe>Cette spécialité à finalité professionnelle est une composante du Master <b>Informatique</b> et du Master <b>Image et Systèmes</b>. Elle est déclinée en trois <b>parcours</b> mais un seul est disponible dans la mention <b>Informatique</b>. Consulter ce parcours pour avoir une information plus précise :</paragraphe>
				<liste>
					<el>Parcours Informatique</el>
				</liste>
			</description>
		</presentation>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/xml/FSIL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="FSIL">
		<presentation>
			<refprof id="denis.lugiez"/>
			<refprof id="jean-luc.massat"/>
			<description>
				<liste>
					<paragraphe>Cette spécialité à finalité professionnelle est une composante du Master Informatique. Elle est déclinée en deux <b>parcours</b> qui partagent un tronc-commun au début de la deuxième année (semestre 3). Consultez ces deux parcours pour avoir une information plus précise :</paragraphe>
					<el>Fiabilité et sécurité informatique (FSI)</el>
					<el>Intégration de systèmes logiciels (ISL)</el>
				</liste>
			</description>
		</presentation>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/bin/xml/ISL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="ISL">
		<presentation>
			<refprof id="jean-luc.massat"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>Le développement de l'Internet/Intranet et des applications associées a fait émerger de nouvelles normes pour la structuration des applications informatiques réparties. L'enjeu est de présenter des modèles (programmation par composants, par aspects, design pattern), des plateformes (JEE, .NET, Corba, etc.) et des outils (JAVA, SGBDOO, XML) qui offrent un cadre dans lequel les applications sont développées, validées et intégrées plus facilement.</paragraphe>
				<paragraphe>L'objectif de ce parcours est d'initier les étudiants à la conception et à la réalisation d'applications dans de tels cadres. La formation mettra plus particulièrement l'accent sur les notions d'architecture logicielle, de programmation par composants, de qualité et de fiabilité. Elle utilisera la plateforme Java Enterprise Edition pour concrétiser les concepts présentés.</paragraphe>
			</description>
		</presentation>
		<competences>
			<liste>
				<el>spécifier, concevoir, réaliser et déployer des applications réparties,</el>
				<el>proposer des architectures informatiques complexes,</el>
				<el>mettre en œuvre des plateformes informatiques professionnelles (JEE, frameworks, etc.),</el>
				<el>synthétiser et présenter une problématique métier (CdC, spécifications, recette, politique de test),</el>
				<el>communiquer en Anglais et en Français.</el>
			</liste>
		</competences>
		<connaissances>
			<paragraphe>L'objectif de la spécialité FSIL est de former des étudiants afin qu'ils puissent concevoir, réaliser, valider et mettre en exploitation des logiciels. Pour ce faire, ils devront connaître les concepts, les outils et les méthodes liés au développement de logiciels. Les aspects de qualité, de sécurité et de bonne intégration dans des environnements informatiques complexes seront les points forts de la formation.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>TC des parcours FSI et ISL</nom>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
				<refunite id="ENSINCU29"/>
				<refunite id="ENSINCU30"/>
				<refunite id="ENSINCU31"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unité d'enseignement à bonus</nom>
				<refunite id="ENSINCU67"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unités obligatoires </nom>
				<refunite id="ENSINCU36"/>
				<refunite id="ENSINCU37"/>
				<refunite id="ENSINCU38"/>
				<refunite id="ENSINCU39"/>
				<refunite id="ENSINCU40"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires </nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>La formation par le biais des projets est largement encouragée : la deuxième année se clôture par un projet de huit semaines en groupe de cinq à six étudiants. C'est l'occasion de mettre en pratique les connaissances acquises durant la formation.</paragraphe>
			<paragraphe>Les stages sont obligatoires en deuxième année (5 à 6 mois). Ils se déroulent en entreprise ou dans un laboratoire suivant les objectifs professionnels de l'étudiant. La recherche de stage est assurée par l'étudiant avec l'aide de l'équipe pédagogique (liste d'entreprises, diffusion des offres reçues, etc.). Le sujet de stage est validé par un enseignant responsable avant la signature de la convention. La fin du stage donne lieu à une soutenance et à la rédaction d 'un mémoire.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>Les membres de l'équipe pédagogique ont une expérience importante en ce qui concerne l'enseignement des bases de données et des applications réparties objets. La plupart des cours spécifiques de ce parcours sont déjà proposés aux étudiants dans le cadre des diplômes actuels depuis plus de 10 ans et régulièrement mis à jour.</paragraphe>
		</aspects_formation>
		<modalites_pedagogiques>
			<liste>
				<paragraphe>L'organisation des enseignements est destinée à renforcer tous les aspects professionnels de la formation. On peut citer notamment :</paragraphe>
				<el>le travail en petit groupe et l'évaluation à base de projets,</el>
				<el>la mise en situation de responsabilité (gestion du parc d'ordinateurs par les étudiants, projet de fin d'année géré directement par les étudiants),</el>
				<el>les nombreux documents à rédiger durant les enseignements,</el>
				<el>les nombreuses présentations orales à effectuer,</el>
				<el>les enseignements spécifiques en Anglais (préparation et passage du TOEIC) et Communication (Lettre de motivation, CV, entretien d'embauche, règles de savoir-être),</el>
				<el>le contact avec des professionnels via les séminaires et les présentations d'entreprises.</el>
			</liste>
		</modalites_pedagogiques>
		<conditions_admission>
			<pre_requis type="obligatoires">
				<liste>
					<el>Être titulaire d'une première année de Master en informatique.</el>
					<el>Avoir de bonnes connaissances en bases de données, langages objets et génie logiciel.</el>
				</liste>
			</pre_requis>
			<pre_requis type="recommandés">
				<liste>
					<el>Avoir de bonnes connaissances en bases de données, langages objets et génie logiciel.</el>
				</liste>
			</pre_requis>
			<paragraphe>L'entrée en deuxième année se fait uniquement sur dossier. Une première année de Master à dominante informatique est requise (60 crédits). Tout autre diplôme de niveau équivalent sera également étudié. La deuxième année du Master est également accessible par le biais de la VAP et de la VAE.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>Les secteurs d'activités concernés sont tous ceux qui utilisent et développent des applications informatiques, avec des pré-requis forts de fiabilité (qualité logicielle) et sécurité (protection contre les actions malveillantes). Les SSII forment une part importante des débouchés mais de grands groupes de l'industrie (transports, électronique, défense,...) ou des services (banques, assurance,..) sont également des employeurs. Les PME innovantes en informatique (éditeurs, prestataires de services, ...) et les collectivités territoriales et établissements publics complètent le secteur d'activité.</paragraphe>
			<liste>
				<paragraphe>Métiers visés pour le parcours FSI :</paragraphe>
				<el>Ingénieur études et développement,</el>
				<el>Responsable réseaux,</el>
				<el>Responsable systèmes et sécurité,</el>
				<el>Ingénieur qualité.</el>
			</liste>
			<liste>
				<paragraphe>Métiers visés par le parcours ISL :</paragraphe>
				<el>Ingénieur études et développement,</el>
				<el>Architecte logiciel,</el>
				<el>Ingénieur en système d'information,</el>
				<el>Expert technique ou fonctionnel.</el>
			</liste>
		</debouches>
		<poursuites>
			<liste>
				<el>Un doctorat est envisageable à l'issue de la spécialité FSIL.</el>
				<el>Les diplômés ont également la possibilité de choisir des formations plus axées sur la gestion des projets scientifiques pourceux qui visent des postes à forte responsabilité.</el>
				<el>Il est également envisageable de suivre une autre spécialité du même master ou d'un autre pour enrichir son portefeuille de compétences.</el>
			</liste>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/bin/xml/ID.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="ID">
		<presentation>
			<refprof id="noel.novelli"/>
			<description>
				<liste>
					<paragraphe>Cette spécialité à finalité professionnelle est une composante du Master Informatique. Elle est déclinée en deux <b>parcours</b> qui partagent un tronc-commun au début de la deuxième année (semestre 3). Consultez ces deux parcours pour avoir une information plus précise :</paragraphe>
					<el>Fouille et entrepôts de données (FED)</el>
					<el>Recherche opérationnelle (RO)</el>
				</liste>
			</description>
		</presentation>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/xml/RO.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="RO">
		<presentation>
			<refprof id="yann.vaxes"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>La recherche opérationnelle consiste à utiliser des méthodes et des modèles pour résoudre des problèmes complexes d'organisation, de planification, de gestion de ressources, ou d'optimisation issus de nombreux secteurs d'activités comme le transport, l'industrie, les télécommunications, la finance... La résolution de ces problèmes constitue un enjeu économique et industriel important. La conception d'applications décisionnelles requiert une phase de spécification et d'extraction de données lors de laquelle les compétences acquises par les étudiants de la spécialité ID dans le domaine de la fouille et des entrepôts de données sera particulièrement utile. Elle nécessite également des connaissances fondamentales dans le domaine de la modélisation et de l'optimisation et une très bonne maîtrise des outils nécessaires pour concevoir et développer des applications décisionnelles (langages de modélisation, solveurs, structures de données, algorithmes…).</paragraphe>
			</description>
		</presentation>
		<competences>
			<liste>
				<el>Anglais, Communication et JEE.</el>
				<el>Créer, maintenir et optimiser des bases de données et/ou des entrepôts de données.</el>
				<el>Mettre en place des solutions de fouilles de données pour diverses domaines comme le marketing, les études de produits et de clientèle, l’aide à la décision, la veille technologique...</el>
				<el>Optimisation combinatoire, programmation mathématique, langages de modélisation, algorithmique des graphes et réseaux.</el>
			</liste>
		</competences>
		<connaissances>
			<paragraphe>Outre les connaissances généralistes comme l’anglais, la communication et JEE (Java Enterprise Edition), les étudiants acquerront les notions fondamentales de l’Informatique Décisionnelle qui regroupe l’administration de bases de données et la modélisation des problèmes (concevoir et constituer un réservoir exploitable de données et définir la stratégie d’exploitation en vue d’une analyse de données), l’optimisation linéaire (modéliser et résoudre un problème d’optimisation), la fouille de bases de données (extraire des informations intéressantes non préalablement connues).</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Tronc-commun des parcours FED et RO </nom>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
				<refunite id="ENSINCU30"/>
				<refunite id="ENSINCU40"/>
				<refunite id="ENSINCU48"/>
				<refunite id="ENSINCU49"/>
				<refunite id="ENSINCU50"/>
				<refunite id="ENSINCU70"/>
				<refunite id="ENSINCU53"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unité d'enseignement à bonus</nom>
				<refunite id="ENSINCU67"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINCU54"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les stages sont optionnels en première année (2 mois), obligatoires en deuxième année (4 à 6 mois). La recherche de stage est assurée par l'étudiant avec l'aide de l'équipe pédagogique (liste d'entreprises, diffusion des offres reçues, etc.). Le sujet de stage est validé par un enseignant responsable avant la signature de la convention. Les sujets doivent vérifier un cahier des charges qui est donné aux étudiants en début d'année. Le stage peut alors débuter. Durant la période de stage, un rapport d'avancement est demandé régulièrement au stagiaire (tous les mois). Les éventuels problèmes sont ainsi décelés au plus tôt. A l'issue du stage, le stagiaire doit fournir un rapport de stage et faire une soutenance orale. Il est noté sur la base de son rapport, de sa présentation et de l'évaluation du stage faite par son tuteur en entreprise.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>En premier lieu, la formation au niveau M1 est caractérisée par un ensemble de cours fondamentaux qui préparent aux spécialités recherche et professionnelles. Ensuite, grâce aux UE optionnelles, les étudiants peuvent choisir des cours plutôt à vocation recherche. Enfin, l'UE projet ou stage peut être dédiée complètement à la recherche : stage dans un laboratoire, ou projet à vocation recherche.</paragraphe>
		</aspects_formation>
		<enseignements_delocalises>
			<paragraphe>Ce master bénéficie de plusieurs contrats Erasmus. Trois contrats de longue date avec les universités de Tübingen et Hannovre (Allemagne) et avec l'université anglophone d'Uppsala (Suède) ont déjà permis des échanges d'étudiants en M1 et M2. Un contrat plus récent avec les université techniques de Munich (Allemagne) et Vienne (Autriche) sont actifs et permettent également des échanges au niveau Master 1 et 2 (le plus souvent sur un semestre), puis au niveau doctoral.</paragraphe>
			<liste>
				<paragraphe>Établissements avec lesquels nous avons un accord Erasmus :</paragraphe>
				<el>Allemagne, Hannovre, Gottfried Wilhelm Leibniz Universität</el>
				<el>Allemagne, Munich, Technische Universität München</el>
				<el>Allemagne, Tübingen, Eberhard Karls Universität</el>
				<el>Vienne, Autriche, Technische Universität Wien</el>
				<el>Suède, Uppsala, Uppsala Universitet</el>
			</liste>
			<liste>
				<paragraphe>Autres établissements avec lesquels nous avons un accord :</paragraphe>
				<el>Belgique, Namur, Facultés Universitaires Notre Dame de la Paix</el>
				<el>Bulgarie, Sofia, Tehnicheski Universitet</el>
				<el>Espagne, Séville, Universidad de Sevilla</el>
				<el>Italie, Sienne, Univ. di Siena</el>
				<el>Roumanie, Brasov, Universitatea Transilvania din Brasov</el>
			</liste>
			<liste>
				<paragraphe>Établissements canadiens avec lesquels nous avons un accord :</paragraphe>
				<el>Université de Montréal</el>
				<el>Université d'Ottawa</el>
				<el>Université de Victoria</el>
				<el>Université Western Ontario</el>
			</liste>
		</enseignements_delocalises>
		<conditions_admission>
			<paragraphe>Après l'étude des dossiers des candidats, le jury d'admission constitué à partir des membres de l'équipe pédagogique statue sur l'admission de chacun d'eux.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<liste>
				<el>Administrateur de bases de données ou d’entrepôts de données.</el>
				<el>Extraction, transformation et chargement des données.</el>
				<el>Gestion, exploitation et optimisation de bases et entrepôts de données.</el>
				<el>Mettre en place et exploiter toutes les phases du processus de l’informatique décisionnelle (compréhension et modélisation du problème, conception du système d’information nécessaire, indicateur de mesure pour réaliser les analyses pour la prise de décisions, les processus de fouille et d’optimisation, la restitution de l’analyse).</el>
				<el>Études et développement informatique.</el>
				<el>Conseil et maîtrise d’ouvrage en système d’information</el>
				<el>Expertise et support technique en système d’information</el>
				<el>Administration de systèmes d'information</el>
			</liste>
		</debouches>
		<poursuites>
			<paragraphe>Il est possible de poursuivre en thèse de doctorat notamment grâce à des bourses CIFRE en partenariat avec des entreprises.</paragraphe>
		</poursuites>
	</parcours>
</master>
