=== TP-XML-LUMINY/Projet/src/dtd/master.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY menu SYSTEM "../xml/menu.xml">
<!ENTITY  programme SYSTEM "../xml/Unites.xml">

<!ELEMENT master (menu?,(parcours)+)>
<!ELEMENT parcours (intervenants?,presentation,competences?,connaissances?,programme*,politique_des_stages?,aspects_formation?,modalites_pedagogiques?,enseignements_delocalises?,conditions_admission?,debouches?,poursuites?)>

<!ELEMENT menu (lien)+>
<!ELEMENT intervenants (enseignant)*>
<!ELEMENT presentation ((enseignant|refprof)*,lieu?,description?)>
<!ELEMENT competences (paragraphe|liste)+>
<!ELEMENT connaissances (paragraphe|liste)+>
<!ELEMENT programme (paquet_unites)*>
<!ELEMENT politique_des_stages (paragraphe|liste)+>
<!ELEMENT aspects_formation (paragraphe|liste)+>
<!ELEMENT modalites_pedagogiques (paragraphe|liste)+>
<!ELEMENT enseignements_delocalises (paragraphe|liste)+>
<!ELEMENT conditions_admission (pre_requis*,paragraphe*,lien)>
<!ELEMENT debouches (paragraphe|liste)+>
<!ELEMENT poursuites (paragraphe|liste)+>

<!ELEMENT enseignant (nom,prenom?,mail+,site_web*)>
<!ELEMENT lieu (campus)+>
<!ELEMENT description (paragraphe|liste)+>
<!ELEMENT paquet_unites (nom?,(unite|refunite)+)>
<!ELEMENT unite (nom,credit,(refprof|resumes|plan|lieu)*)>
<!ELEMENT refunite EMPTY>
<!ELEMENT plan (nom,nb_h)>
<!ELEMENT resumes (((paragraphe|chapitre|liste)+,pre_requis?)|(absent))>
<!ELEMENT absent EMPTY>
<!ELEMENT chapitre (titre,(paragraphe|liste)*)>
<!ELEMENT pre_requis (paragraphe|liste)+>

<!ELEMENT nb_h (#PCDATA)>
<!ELEMENT titre (#PCDATA|b|i|tt|u)*>
<!ELEMENT nom (#PCDATA|b|i|tt|u)*>
<!ELEMENT prenom (#PCDATA|b|i|tt|u)*>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT campus (#PCDATA|b|i|tt|u)*>
<!ELEMENT paragraphe (#PCDATA|b|i|tt|u|liste)*>
<!ELEMENT site_web (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT refprof EMPTY>
<!ELEMENT resume (#PCDATA|b|i|tt|u)*>
<!ELEMENT lien (#PCDATA|b|i|tt|u)*>
<!ELEMENT liste (paragraphe?,(el)+)>

<!ELEMENT el (#PCDATA|b|i|tt|u)*>
<!ELEMENT b	(#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT tt (#PCDATA)>
<!ELEMENT u (#PCDATA)>

<!ATTLIST pre_requis
	type CDATA #IMPLIED
	>
<!ATTLIST liste
	type CDATA "ul"
	>
<!ATTLIST parcours
	annee CDATA #REQUIRED
	>
<!ATTLIST programme
	semestre CDATA #REQUIRED
	>
<!ATTLIST enseignant
	id ID #IMPLIED
	>
<!ATTLIST unite
	id ID #REQUIRED
	>
<!ATTLIST refunite
	id CDATA #REQUIRED
	>
<!ATTLIST ref
	idref IDREF #REQUIRED
	>
<!ATTLIST refprof
	id CDATA #REQUIRED
	>
<!ATTLIST lien
	link CDATA #REQUIRED
	class CDATA #IMPLIED
	>

=== TP-XML-LUMINY/Projet/xml/INF.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="INF">
		<presentation>
			<refprof id="nicola.olivetti"/>
			<lieu>
				<campus>Campus de Saint-Jérôme</campus>
			</lieu>
			<description>
				<paragraphe>L’objectif est d’approfondir les connaissances de bases en Informatique sur l’intelligence artificielle, les systèmes d’information, conception et vérification des systèmes, informatique décisionnelle.</paragraphe>
			</description>
		</presentation>
		<competences>
			<paragraphe>Les compétences relèvent des thématiques de recherche suivantes : Fondements Logiques et Algorithmiques ; Fondements de programmation par contraintes et satisfiabilité ; Représentation des connaissances : approfondissement et applications ; Planification, configuration et raisonnement temporel et spatial ; Agents et ontologies pour les systèmes d’information et le web sémantique ; Approches avancées de conception de systèmes d’information ; Extraction et intégration d'information du web ; Web services ; Aide à la décision ; Formalismes à événements discrets.</paragraphe>
		</competences>
		<connaissances>
			<paragraphe>Aptitude à la recherche et à la veille technologique.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSISCU20"/>
			</paquet_unites>
			<paquet_unites>
				<nom>15 crédits à choisir parmi</nom>
				<refunite id="ENSISCU21"/>
				<refunite id="ENSISCU22"/>
				<refunite id="ENSISCU23"/>
				<refunite id="ENSISCU24"/>
				<refunite id="ENSISCU25"/>
				<refunite id="ENSISCU26"/>
				<refunite id="ENSISCU27"/>
				<refunite id="ENSISCU28"/>
				<refunite id="ENSISCU29"/>
				<refunite id="ENSISCU30"/>
				<refunite id="ENSISCU31"/>
				<refunite id="ENSISCU32"/>
			</paquet_unites>
			<paquet_unites>
				<nom>9 crédits à choisir parmi </nom>
				<refunite id="ENSISCU1"/>
				<refunite id="ENSISCU4"/>
				<refunite id="ENSISCU5"/>
				<refunite id="ENSISCU6"/>
				<refunite id="ENSISCU7"/>
				<refunite id="ENSISCU8"/>
				<refunite id="ENSISCU55"/>
				<refunite id="ENSISCU3"/>
				<refunite id="ENSISCU2"/>
				<refunite id="ENSISCU33"/>
				<refunite id="ENSISCU34"/>
				<refunite id="ENSISCU35"/>
				<refunite id="ENSISCU36"/>
				<refunite id="ENSISCU37"/>
				<refunite id="ENSISCU38"/>
				<refunite id="ENSISCU39"/>
				<refunite id="ENSISCU40"/>
				<refunite id="ENSISCU41"/>
				<refunite id="ENSISCU42"/>
				<refunite id="ENSISCU43"/>
				<refunite id="ENSISCU44"/>
				<refunite id="ENSISCU45"/>
				<refunite id="ENSISCU46"/>
				<refunite id="ENSISCU21"/>
				<refunite id="ENSISCU22"/>
				<refunite id="ENSISCU23"/>
				<refunite id="ENSISCU24"/>
				<refunite id="ENSISCU25"/>
				<refunite id="ENSISCU26"/>
				<refunite id="ENSISCU27"/>
				<refunite id="ENSISCU28"/>
				<refunite id="ENSISCU29"/>
				<refunite id="ENSISCU30"/>
				<refunite id="ENSISCU32"/>
				<refunite id="ENSISCU31"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSISDU3"/>
				<refunite id="ENSISDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Stage de recherche en laboratoire de 4 mois précédé par une étude bibliographique.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>Cette spécialité est adossée au Laboratoire des Sciences de l’Information et des Systèmes (LSIS, UMR CNRS 6168) et aborde les thèmes de recherche développés dans les trois pôles de ce laboratoire : informatique, systèmes et image. Ce laboratoire met à disposition des étudiants, toutes ses thématiques scientifiques lors de la formation disciplinaires du S3 et accueille les étudiants pour leur stage du S4.</paragraphe>
		</aspects_formation>
		<conditions_admission>
			<paragraphe>Admission sur dossier.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<liste>
				<paragraphe>Enseignants, Chercheurs et ingénieurs de recherche, experts, chef de projets R&#38;D en :</paragraphe>
				<el>systèmes d'information,</el>
				<el>intelligence artificielle,</el>
				<el>génie logiciel,</el>
				<el>imagerie numérique.</el>
			</liste>
		</debouches>
		<poursuites>
			<paragraphe>Doctorat dans les domaines de l'Informatique et de l'Imagerie Numérique.</paragraphe>
		</poursuites>
	</parcours>
</master>
