=== TP-XML-LUMINY/Projet/src/dtd/master.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY menu SYSTEM "../xml/menu.xml">
<!ENTITY  programme SYSTEM "../xml/Unites.xml">

<!ELEMENT master (menu?,(parcours)+)>
<!ELEMENT parcours (intervenants?,presentation,competences?,connaissances?,programme*,politique_des_stages?,aspects_formation?,modalites_pedagogiques?,enseignements_delocalises?,conditions_admission?,debouches?,poursuites?)>

<!ELEMENT menu (lien)+>
<!ELEMENT intervenants (enseignant)*>
<!ELEMENT presentation ((enseignant|refprof)*,lieu?,description?)>
<!ELEMENT competences (paragraphe|liste)+>
<!ELEMENT connaissances (paragraphe|liste)+>
<!ELEMENT programme (paquet_unites)*>
<!ELEMENT politique_des_stages (paragraphe|liste)+>
<!ELEMENT aspects_formation (paragraphe|liste)+>
<!ELEMENT modalites_pedagogiques (paragraphe|liste)+>
<!ELEMENT enseignements_delocalises (paragraphe|liste)+>
<!ELEMENT conditions_admission (pre_requis*,paragraphe*,lien)>
<!ELEMENT debouches (paragraphe|liste)+>
<!ELEMENT poursuites (paragraphe|liste)+>

<!ELEMENT enseignant (nom,prenom?,mail+,site_web*)>
<!ELEMENT lieu (campus)+>
<!ELEMENT description (paragraphe|liste)+>
<!ELEMENT paquet_unites (nom?,(unite|refunite)+)>
<!ELEMENT unite (nom,credit,(refprof|resumes|plan|lieu)*)>
<!ELEMENT refunite EMPTY>
<!ELEMENT plan (nom,nb_h)>
<!ELEMENT resumes (((paragraphe|chapitre|liste)+,pre_requis?)|(absent))>
<!ELEMENT absent EMPTY>
<!ELEMENT chapitre (titre,(paragraphe|liste)*)>
<!ELEMENT pre_requis (paragraphe|liste)+>

<!ELEMENT nb_h (#PCDATA)>
<!ELEMENT titre (#PCDATA|b|i|tt|u)*>
<!ELEMENT nom (#PCDATA|b|i|tt|u)*>
<!ELEMENT prenom (#PCDATA|b|i|tt|u)*>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT campus (#PCDATA|b|i|tt|u)*>
<!ELEMENT paragraphe (#PCDATA|b|i|tt|u|liste)*>
<!ELEMENT site_web (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT refprof EMPTY>
<!ELEMENT resume (#PCDATA|b|i|tt|u)*>
<!ELEMENT lien (#PCDATA|b|i|tt|u)*>
<!ELEMENT liste (paragraphe?,(el)+)>

<!ELEMENT el (#PCDATA|b|i|tt|u)*>
<!ELEMENT b	(#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT tt (#PCDATA)>
<!ELEMENT u (#PCDATA)>

<!ATTLIST pre_requis
	type CDATA #IMPLIED
	>
<!ATTLIST liste
	type CDATA "ul"
	>
<!ATTLIST parcours
	annee CDATA #REQUIRED
	>
<!ATTLIST programme
	semestre CDATA #REQUIRED
	>
<!ATTLIST enseignant
	id ID #IMPLIED
	>
<!ATTLIST unite
	id ID #REQUIRED
	>
<!ATTLIST refunite
	id CDATA #REQUIRED
	>
<!ATTLIST ref
	idref IDREF #REQUIRED
	>
<!ATTLIST refprof
	id CDATA #REQUIRED
	>
<!ATTLIST lien
	link CDATA #REQUIRED
	class CDATA #IMPLIED
	>

=== TP-XML-LUMINY/Projet/bin/xml/GL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="GL">
		<presentation>
			<refprof id="djamal.habet"/>
			<lieu>
				<campus>Campus de Saint-Jérôme</campus>
			</lieu>
			<description>
				<paragraphe>La production d'un logiciel est une tâche très complexe mettant en oeuvre plusieurs ressources, notamment humaines, matériels et technologiques. La spécialité « Génie logiciel » a pour objectif d'apporter aux étudiants les compétences approfondies requises pour pouvoir intervenir dans toutes les phases de la production logiciel.</paragraphe>
			</description>
		</presentation>
		<competences>
			<paragraphe>Le diplômé acquiers les compétences approfondies pour être capable d'intervenir dans toutes les phases du cycle de vie d'un logiciel à la fois au niveau de la conception et la spécification (patrons de conception, UML ...), des architectures et composants logiciels (JEE ...), des IHM, de la qualité logicielle, de la validation logiciels, des ateliers de génie logiciels et des technologies du Web. La gestion de projet est aussi aborder pour la maîtrise des grands projets informatiques.</paragraphe>
		</competences>
		<connaissances>
			<paragraphe>La spécialité « Génie logiciel » a pour objectif d'apporter aux étudiants les compétences approfondies requises pour pouvoir intervenir dans toutes les phases de la production logiciel à la fois au niveau de la conception et la spécification (patrons de conception, UML ...), des architectures et composants logiciels (JEE ...), des IHM, de la qualité logicielle, de la validation logiciels, des ateliers de génie logiciels et des technologies du Web. La gestion de projet est aussi aborder pour la maîtrise des grands projets informatiques.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Unités obligatoires </nom>
				<refunite id="ENSINCU41"/>
				<refunite id="ENSINCU42"/>
				<refunite id="ENSINCU43"/>
				<refunite id="ENSINCU44"/>
				<refunite id="ENSINCU45"/>
				<refunite id="ENSINCU46"/>
				<refunite id="ENSINCU47"/>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les stages en entreprise sont obligatoires (avec une durée de 4 à 6 mois). La recherche de stage est assurée par l'étudiant avec l'aide de l'équipe pédagogique (liste d'entreprises, diffusion des offres reçues).</paragraphe>
			<paragraphe>Le sujet de stage est validé par un enseignant responsable avant la signature de la convention. Les sujets doivent vérifier un cahier des charges qui est donné aux étudiants en début d'année. Le stage peut alors débuter.</paragraphe>
			<paragraphe>Durant la période de stage, un rapport d'avancement est demandé régulièrement au stagiaire (tous les mois). Les éventuels problèmes sont ainsi décelés au plus tôt. A l'issue du stage, le stagiaire doit fournir un rapport de stage et faire une soutenance orale. Il est noté sur la base de son rapport, de sa présentation et de l'évaluation du stage faite par son tuteur en entreprise.</paragraphe>
		</politique_des_stages>
		<conditions_admission>
			<pre_requis type="obligatoires">
				<paragraphe>Une première année de Master à dominante informatique (60 crédits) ou tout diplôme équivalent.</paragraphe>
			</pre_requis>
			<paragraphe>L'entrée à la spécialité Génie logiciel se fait uniquement sur dossier. Une première année de Master à dominante informatique est requise (60 crédits). Tout autre diplôme de niveau équivalent sera également étudié. La deuxième année du Master est également accessible par le biais de la VAP et de la VAE.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>Ingénieur informaticien, Ingénieur d’études et de développement, Ingénieur qualité logicielle, Architecte JEE, Architecte d’applications, Développeur et concepteur d’applications, Ingénieur développeur Web, Chef de projets, Consultant.</paragraphe>
		</debouches>
		<poursuites>
			<paragraphe>Les diplômés peuvent poursuivre des formations plus axées sur la gestion des projets scientifiques pour ceux qui visent des postes à forte responsabilité. La préparation d'un doctorat est également possible.</paragraphe>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/src/xml/RIM.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="RIM">
		<presentation>
			<refprof id="frederic.bechet"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>L'objectif de la spécialité RIM est de former des spécialistes du traitement et de la recherche de contenus multimédias. Du point de vue des débouchés professionnels, cette formation vise à produire des informaticiens spécialistes du traitement des données multimédia et de la recherche d'information qui pourront s'intégrer dans des entreprises innovantes centrées autour des domaines du multimédia et de l'internet.</paragraphe>
			</description>
		</presentation>
		<competences>
			<paragraphe>Les enseignements sont organisés selon deux axes : l'analyse et la représentation du contenu d'une part ; l'indexation et la recherche d'information d'autre part. L'analyse et le traitement du contenu désignent les traitements de fichiers texte, audio, image ou vidéo permettant d'obtenir une représentation structurée de leur contenu sous forme de descripteurs, du niveau signal au niveau sémantique. L'indexation consiste à utiliser ces descripteurs afin d'indexer finement chaque document pour procéder à son archivage de façon optimisée.</paragraphe>
		</competences>
		<connaissances>
			<paragraphe>L'objectif de la spécialité RIM est de former des spécialistes du traitement et de la recherche de contenus multimédias sur internet. Les enseignements sont organisés selon deux axes : l'analyse et la représentation du contenu d'une part ; l'indexation et la recherche d'information d'autre part. L'analyse et le traitement du contenu désignent les traitements de fichiers texte, audio, image ou vidéo permettant d'obtenir une représentation structurée de leur contenu sous forme de descripteurs, du niveau signal au niveau sémantique.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Unité d'enseignement à bonus</nom>
				<refunite id="ENSINCU67"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINCU56"/>
				<refunite id="ENSINCU58"/>
				<refunite id="ENSINCU59"/>
				<refunite id="ENSINCU66"/>
				<refunite id="ENSINCU69"/>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
			</paquet_unites>
			<paquet_unites>
				<nom>3 crédits à choisir parmi </nom>
				<refunite id="ENSINCU4"/>
				<refunite id="ENSINCU5"/>
				<refunite id="ENSINCU6"/>
				<refunite id="ENSINCU7"/>
				<refunite id="ENSINCU19"/>
				<refunite id="ENSINCU20"/>
				<refunite id="ENSINCU21"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les stages doivent être effectués soit dans une entreprise, soit dans un laboratoire de recherche ayant un lien fort avec la thématique de la spécialité. Les sujets des projets de fin d'étude pourront avoir été proposés par des professionnels, l'encadrement est réalisé par l'équipe pédagogique.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>Cette spécialité repose sur les compétences de deux équipes du LIF : l'équipe TALEP qui apportera ses compétences dans le domaine du traitement des contenus textuels et audio et l'équipe Apprentissage Automatique qui apportera ses compétences dans le domaine de la classification et de l'annotation de données multimodales.</paragraphe>
		</aspects_formation>
		<modalites_pedagogiques>
			<paragraphe>Les enseignements seront partagés entre des cours et du travail pratique, soit TD soit TP, selon les matières. Une part importante du travail personnel sera consacrée à la réalisation de projets concrets, communs à plusieurs enseignements, représentant des cas d'études réalistes de prototypes de traitements de données multimédia.</paragraphe>
		</modalites_pedagogiques>
		<conditions_admission>
			<pre_requis type="obligatoires">
				<paragraphe>Une première année de Master informatique est requise (60 crédits). Tout autre diplôme de niveau équivalent sera également étudié (ainsi que VAP et VAE)</paragraphe>
			</pre_requis>
			<paragraphe>L'entrée en deuxième année se fait uniquement sur dossier. Une première année de Master informatique est requise (60 crédits). Tout autre diplôme de niveau équivalent sera également étudié (ainsi que VAP et VAE).</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>Cette formation vise à produire des informaticiens spécialistes du traitement des données multimédia et de la recherche d'information qui pourront s'intégrer dans les entreprises innovantes centrées autour des domaines du multimédia et de l'internet.</paragraphe>
		</debouches>
		<poursuites>
			<paragraphe>Une poursuite en thèse pourra être envisagée si le stage de fin d'étude s'effectue au sein d'un laboratoire de recherche.</paragraphe>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/xml/FSI.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="FSI">
		<presentation>
			<refprof id="denis.lugiez"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>La formation donne les principes et techniques liés à la conception de systèmes informatiques surs dans un environnement ouvert et hétérogène. Elle forme les étudiants aux principes et méthodes de développement modernes qui reposent sur des outils de prototypage, de test et de suivi de logiciels, avec des méthodologies normalisées. Elle apporte des compétences fortes en sécurité informatique dans les domaines liés à l'échange d'information (Web-services, protocoles de communication et cryptographiques,..) et à la communication entre systèmes (réseaux hétérogènes et applications embarquées ou distribuées).</paragraphe>
			</description>
		</presentation>
		<competences>
			<liste>
				<el>Anglais, Communication, Gestion de projet</el>
				<el>Méthode de développement logiciel (Spécification, Tests, Evaluation de performance)</el>
				<el>Savoir définir et mettre en œuvre les méthodes de sécurité informatique dans un environnement distribué et ouvert</el>
				<el>Savoir spécifier, concevoir et réaliser un système logiciel et matériel complexe</el>
				<el>Programmation de systèmes embarqués</el>
			</liste>
		</competences>
		<connaissances>
			<paragraphe>L'objectif de la spécialité FSIL est de former des étudiants afin qu'ils puissent concevoir, réaliser, valider et mettre en exploitation des logiciels. Pour ce faire, ils devront connaître les concepts, les outils et les méthodes liés au développement de logiciels. Les aspects de qualité, de sécurité et de bonne intégration dans des environnements informatiques complexes seront les points forts de la formation.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>TC des parcours FSI et ISL</nom>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
				<refunite id="ENSINCU29"/>
				<refunite id="ENSINCU30"/>
				<refunite id="ENSINCU31"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unité d'enseignement à bonus</nom>
				<refunite id="ENSINCU67"/>
			</paquet_unites>
			<paquet_unites>
				<nom>Unités obligatoires </nom>
				<refunite id="ENSINCU32"/>
				<refunite id="ENSINCU33"/>
				<refunite id="ENSINCU34"/>
				<refunite id="ENSINCU35"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires </nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les stages sont optionnels en première année (2 mois), obligatoires en deuxième année (4 à 6 mois). La recherche de stage est assurée par l'étudiant avec l'aide de l'équipe pédagogique (liste d'entreprises, diffusion des offres reçues, etc.). Le sujet de stage est validé par un enseignant responsable avant la signature de la convention. Les sujets doivent vérifier un cahier des charges qui est donné aux étudiants en début d'année. Le stage peut alors débuter. Durant la période de stage, un rapport d'avancement est demandé régulièrement au stagiaire (tous les mois). Les éventuels problèmes sont ainsi décelés au plus tôt. A l'issue du stage, le stagiaire doit fournir un rapport de stage et faire une soutenance orale. Il est noté sur la base de son rapport, de sa présentation et de l'évaluation du stage faite par son tuteur en entreprise.</paragraphe>
		</politique_des_stages>
		<conditions_admission>
			<pre_requis>
				<paragraphe>L'entrée en deuxième année se fait uniquement sur dossier. Une première année de Master à dominante informatique est requise (60 crédits). Tout autre diplôme de niveau équivalent sera également étudié. La deuxième année du Master est également accessible par le biais de la VAP et de la VAE.</paragraphe>
			</pre_requis>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>Les secteurs d'activités concernés sont tous ceux qui utilisent et développent des applications informatiques, avec des pré-requis forts de fiabilité (qualité logicielle) et sécurité (protection contre les actions malveillantes). Les SSII forment une part importante des débouchés mais de grands groupes de l'industrie (transports, électronique, défense,...) ou des services (banques, assurance,..) sont également des employeurs. Les PME innovantes en informatique (éditeurs, prestataires de services, ...) et les collectivités territoriales et établissements publics complètent le secteur d'activité.</paragraphe>
			<liste>
				<paragraphe>Métiers visés pour le parcours FSI :</paragraphe>
				<el>Ingénieur études et développement,</el>
				<el>Responsable réseaux,</el>
				<el>Responsable systèmes et sécurité,</el>
				<el>Ingénieur qualité.</el>
			</liste>
			<liste>
				<paragraphe>Métiers visés par le parcours ISL :</paragraphe>
				<el>Ingénieur études et développement,</el>
				<el>Architecte logiciel,</el>
				<el>Ingénieur en système d'information,</el>
				<el>Expert technique ou fonctionnel.</el>
			</liste>
		</debouches>
		<poursuites>
			<liste>
				<el>Un doctorat est envisageable à l'issue de la spécialité FSIL.</el>
				<el>Les diplômés ont également la possibilité de choisir des formations plus axées sur la gestion des projets scientifiques pourceux qui visent des postes à forte responsabilité.</el>
				<el>Il est également envisageable de suivre une autre spécialité du même master ou d'un autre pour enrichir son portefeuille de compétences.</el>
			</liste>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/xml/IF.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	<parcours annee="IF">
		<presentation>
			<refprof id="hery-liva.ralaivola"/>
			<refprof id="pierre-alain.reynier"/>
			<lieu>
				<campus>Campus de Luminy</campus>
			</lieu>
			<description>
				<paragraphe>L'objectif de la spécialité Informatique Fondamentale est de donner des connaissances solides dans le domaine des fondements de l'informatique. Il s'agit d'acquérir des connaissances sur les concepts et les méthodes dans l es thèmes couverts par le Laboratoire d'Informatique Fondamentale.</paragraphe>
			</description>
		</presentation>
		<competences>
			<paragraphe>En termes de compétences cette spécialité a pour but de développer chez les étudiants leur capacité à raisonner et à for, et de les initier à la recherche.</paragraphe>
			<paragraphe>Cette spécialité de master a pour vocation de former des diplômés en informatique capables d'occuper des postes d'enseignant-chercheur ou de chercheur, ou tout poste lié à la recherche dans les organismes de recherche publics ou privés.</paragraphe>
		</competences>
		<connaissances>
			<paragraphe>L'objectif de la spécialité Informatique Fondamentale est de donner des connaissances solides dans le domaine des fondements de l'informatique.</paragraphe>
			<paragraphe>Il s'agit d'acquérir des connaissances sur les concepts et les méthodes dans les thèmes couverts par le laboratoire d'informatique fondamentale.</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINCU1"/>
				<refunite id="ENSINCU2"/>
				<refunite id="ENSINCU3"/>
			</paquet_unites>
			<paquet_unites>
				<nom>15 crédits à choisir (validation requise)</nom>
				<refunite id="ENSINCU4"/>
				<refunite id="ENSINCU5"/>
				<refunite id="ENSINCU6"/>
				<refunite id="ENSINCU7"/>
				<refunite id="ENSINCU8"/>
				<refunite id="ENSINCU9"/>
				<refunite id="ENSINCU10"/>
				<refunite id="ENSINCU11"/>
				<refunite id="ENSINCU12"/>
				<refunite id="ENSINCU13"/>
				<refunite id="ENSINCU14"/>
				<refunite id="ENSINCU15"/>
				<refunite id="ENSINCU16"/>
				<refunite id="ENSINCU17"/>
				<refunite id="ENSINCU18"/>
				<refunite id="ENSINCU19"/>
				<refunite id="ENSINCU20"/>
				<refunite id="ENSINCU21"/>
				<refunite id="ENSINCU22"/>
				<refunite id="ENSINCU23"/>
				<refunite id="ENSINCU24"/>
				<refunite id="ENSINCU25"/>
				<refunite id="ENSINCU26"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU1"/>
				<refunite id="ENSINDU2"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Stage dans un laboratoire de recherche.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>La formation est caractérisée par un ensemble de cours fondamentaux qui préparent aux UE optionnelles, pour lesquelles les étudiants peuvent choisir des cours plutôt à vocation recherche. Enfin, l'UE projet ou stage peut être dédiée complètement à la recherche : stage dans un laboratoire, ou projet à vocation recherche.</paragraphe>
		</aspects_formation>
		<enseignements_delocalises>
			<paragraphe>Ce master bénéficie de plusieurs contrats Erasmus. Ils permettent des échanges au niveau Master 1 et 2 (le plus souvent sur un semestre),puis au niveau doctoral.</paragraphe>
		</enseignements_delocalises>
		<conditions_admission>
			<pre_requis type="obligatoires">
				<paragraphe>M1 à dominante informatique.</paragraphe>
			</pre_requis>
			<paragraphe>L'entrée en deuxième année se fait uniquement sur dossier. Une première année de Master à dominante informatique est requise (60 crédits).</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>Emplois recherche et développement dans des entreprises privées ou des établissements publics, ou emploi d'enseignant-chercheur pour les étudiants qui poursuivent en thèse.</paragraphe>
		</debouches>
		<poursuites>
			<paragraphe>Les étudiants ayant obtenu une mention peuvent raisonnablement espérer obtenir une bourse par divers biais pour continuer en thèse.</paragraphe>
		</poursuites>
	</parcours>
</master>

=== TP-XML-LUMINY/Projet/src/xml/SIR.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../xsl/master.xsl" type="text/xsl" media="screen"?>
<!DOCTYPE masterInfo SYSTEM "../dtd/master.dtd">

<master>
	&menu;
	<parcours annee="SIR">
		<presentation>
			<refprof id="omar.boucelma"/>
			<lieu>
				<campus>Campus de Saint-Jérôme</campus>
			</lieu>
			<description>
				<paragraphe>Le programme vise la formation de spécialistes dans des métiers à forte valeur ajoutée au travers des compétences acquises dans trois domaines clés de l’informatique : les technologies avancées du Web (services web, multimédia, etc.), les nouveaux modes de développement du logiciel (Cloud, Mobile, etc.) et les processus métiers de l’entreprise.</paragraphe>
			</description>
		</presentation>
		<competences>
			<liste>
				<el>Réaliser des systèmes d’information répartis sur Internet à l’aide d’architectures de type JEE ou SOA.</el>
				<el>Maîtriser les nouvelles technologies logicielles&#160;: Services Web, Cloud Computing, et applications Mobiles.</el>
				<el>Développer et exploiter les Réseaux Sociaux pour des applications d’entreprise et grand public.</el>
				<el>Maîtriser des technologies logicielles clés pour l’entreprise (BPM, ERP, etc.).</el>
				<el>Acquérir des compétences en management de projet.</el>
			</liste>
		</competences>
		<connaissances>
			<paragraphe>Durant la formation, l’étudiant consolidera d’abord ses connaissances de base dans le domaine des logiciels et systèmes d’information répartis (architecture N-tier, JEE, etc.). Par la suite, il effectuera une montée en compétence dans les technologies suivantes : les technologies avancées du Web (Services Web, Réseaux Sociaux, Multimédia, etc.), les nouvelles architectures logicielles (SOA, Cloud), les Réseaux Sociaux, la programmation Mobile ou encore les processus métiers (BPM, ERP, etc).</paragraphe>
		</connaissances>
		<programme semestre="3">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINCU60"/>
				<refunite id="ENSINCU61"/>
				<refunite id="ENSINCU63"/>
				<refunite id="ENSINCU64"/>
				<refunite id="ENSINCU65"/>
				<refunite id="ENSINCU68"/>
				<refunite id="ENSINCU27"/>
				<refunite id="ENSINCU28"/>
			</paquet_unites>
		</programme>
		<programme semestre="4">
			<paquet_unites>
				<nom>Unités obligatoires</nom>
				<refunite id="ENSINDU3"/>
				<refunite id="ENSINDU4"/>
			</paquet_unites>
		</programme>
		<politique_des_stages>
			<paragraphe>Les étudiants sont fortement encouragés à trouver le stage, d’une durée de 5 à 6 mois, en adéquation avec leur projet professionnel. La validation du sujet de stage est effectuée par l’équipe pédagogique. Le projet tutoré, en liaison éventuelle avec un partenaire industriel permet une mise en œuvre pratique à échelle réelle.</paragraphe>
		</politique_des_stages>
		<aspects_formation>
			<paragraphe>La formation est fortement adossée à la recherche : les enseignants chercheurs membres de l'équipe pédagogique effectuent leur recherche dans les domaines de compétence visés par la formation. L’équipe a contribué dans les domaines suivants : intégration de données hétérogènes et réparties, services web, technologies XML, e-Learning, personnalisation pour les Mobiles, et sécurité dans le Cloud.</paragraphe>
			<paragraphe>Ce lien enseignement-recherche assure une actualisation pérenne des programmes et une anticipation des demandes issues de la profession.</paragraphe>
		</aspects_formation>
		<conditions_admission>
			<pre_requis type="obligatoires">
				<paragraphe>Compétences acquises à la sortie d’un Master 1 Informatique.</paragraphe>
			</pre_requis>
			<pre_requis type="recommandés">
				<liste>
					<el>Connaissance des briques de base qui composent une architecture répartie : bases de données, Java, XML</el>
					<el>Appétence pour les nouvelles technologies</el>
				</liste>
			</pre_requis>
			<paragraphe>L’admission en M2 se fait sur dossier pour les étudiants titulaires d'un M1 informatique ou équivalent. L’admission est possible pour le public en formation continue dans le cadre de la VAE ou VAP.</paragraphe>
			<lien link="http://masterinfo.univ-mrs.fr/candidature/">Déposer une candidature pour 2014/2015.</lien>
		</conditions_admission>
		<debouches>
			<paragraphe>La spécialité SIR vise des métiers de l’informatique à forte valeur ajoutée grâce aux compétences acquises dans trois domaines clés : les technologies avancées du Web, les nouveaux modes de développement et de déploiement de solutions logicielles et les processus métiers de l’entreprise.</paragraphe>
			<liste>
				<paragraphe>Parmi les métiers visés on trouve :</paragraphe>
				<el>Architecte en Systèmes d’Information,</el>
				<el>Ingénieur Développement Logiciels,</el>
				<el>Ingénieur Intégration,</el>
				<el>Consultant ERP/BPM,</el>
				<el>Chef de projet.</el>
			</liste>
		</debouches>
		<poursuites>
			<paragraphe>La poursuite d'études en doctorat est envisageable.</paragraphe>
		</poursuites>
	</parcours>
</master>
